### PR TITLE
Upgrade pgx and add go modules

### PR DESCRIPTION
**Pull request by gadelkareem**
- Upgrade pgx to v4
- Add go modules
- Add docker-compose for postgres
- Run test on Travis

Instead of #36 

# CI
https://travis-ci.org/github/gadelkareem/que/builds/736319827

### CODE REVIEW

**Comment by grippy** [comment]
@gadelkareem I saw your comment on the previous branch. I'm not the maintainer. Was it previously communicated this package is no longer being maintained? Sorry, just trying to determine how I should proceed with some changes I'd like to propose.

**Comment by gadelkareem** [comment]
@grippy Actually I have no idea. I send the PR long ago but I did not get a reply to I just started to use my fork https://github.com/gadelkareem/que

**Comment by chesnokovilya** [comment]
up

**Comment by bgentry** [comment]
Hi all, I recommend you check out my new project, [River](https://github.com/riverqueue/river). River already does quite a bit more than que-go, uses a much more scalable design, and is designed for modern Go and pgx/v5.

I will be archiving this repository shortly.

**Pull request closed without merging**
